services:

  api-server:
    image: eclipse-temurin:25
    command: ./mvnw -DskipTests spring-boot:run -Dspring-boot.run.profiles=oauth2
    volumes:
      - ./api-server:/app
      - ~/.m2:/root/.m2
    working_dir: /app

  api-client:
    image: eclipse-temurin:25
    command: ./mvnw -DskipTests spring-boot:run -Dspring-boot.run.profiles=oauth2
    volumes:
      - ./api-client:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    secrets:
      - oauth2_client_secret
    ports:
      - "8080:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

secrets:
  oauth2_client_secret:
    file: ./terraform/client_secret